---
title: "Air Drag Representation"
author: "Aguado, B.; Jorges, B.; López-Moliner, J."
date: "2/10/2019"
output:   pdf_document
editor_options:
  chunk_output_type: console
---

<!-- SETUP CHUNK -->

```{r, SETUP, echo=FALSE, warning=FALSE, message=FALSE, results="asis", include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, results="asis")
set.seed(80085)

libraries <- c("cowplot","tidyverse","grid","gridExtra","lme4","lmerTest","ggpubr","apastats","rstatix")
# Where is this script?
invisible(lapply(libraries, function(x) {
    if(!require(x, character.only = T, quietly = T)) {
      install.packages(x)
      require(x, character.only = T)
    }
  }
))
rm(libraries)

Where_Am_I <- function(path=T){
  if (path == T){
    dirname(rstudioapi::getSourceEditorContext()$path)
  }
  else {
    rstudioapi::getSourceEditorContext()$path
  }
}
theme_set(theme_minimal(10))
scale_color_discrete <- function(...) {
  ggthemes::scale_color_colorblind(...)
}
scale_fill_discrete <- function(...) {
  ggthemes::scale_fill_colorblind(...)
}
source("Utilities/Funs.R")

```

```{r, eval = F}
# Set working directory as the R script directory
setwd(Where_Am_I())
```


<!-- EXPERIMENTAL CONDITIONS -->

```{r, EXPERIMENTAL_PARAMETERS}
# =============================================================================
# Experimental parameters
# =============================================================================
Exp_Conds <- expand.grid(Xi = 0,
                         Yi = 0,
                         vx = c(3,3.5),
                         vy = c(1,1.2,1.4)*9.807/2,
                         ball = c("tennis","basket"),
                         cond_size = c("cong","incongr"),
                         air_drag = c(1,0), rho = 1.225,
                         G = 9.807) %>%
  mutate(m = ifelse(ball == "tennis",
                    ifelse(cond_size == "cong",0.06,0.6),
                    ifelse(ball == "basket",
                           ifelse(cond_size == "cong",0.6,0.06),NA)),
         r = ifelse(ball == "tennis",
                    ifelse(cond_size == "cong",0.033,0.12),
                    ifelse(ball == "basket",
                           ifelse(cond_size == "cong",0.12,0.033),NA)),
         TTC = vy * 2 /9.807, 
         v = sqrt(vx^2+vy^2),
         cd = ifelse(air_drag == 0, 0, 0.535),
         id_TTC = paste0(ifelse(air_drag == 1, "Air_Drag_","Gravity_"),TTC),
         id_cond = paste0(id_TTC,"_",ball,"_",cond_size),
         id_exp = paste0(id_cond,"_vx_",vx), # Condition long identifier for experiment
         label = 1:n()) # Condition identifier for experiment

# =============================================================================
# Experimental conditions with max values
# =============================================================================
Exp_Conds <- Exp_Conds %>%
  group_by(air_drag,ball,cond_size,id_cond,m,r,rho,cd,TTC,id_TTC,v,G,vy,vx,Xi,Yi,id_exp,label) %>%
  do(xy_drag(vh = .$vx, vv = .$vy,C = .$cd,
             rho = .$rho,m = .$m,radius = .$r,
             dt = 0.001,g = .$G,vectors = F)) %>%
  summarize(x_max = max(x),
            y_max = max(y),
            t_max = max(t))  %>%
  ungroup() 


# =============================================================================
# Continuous
# =============================================================================
Continuous <- Exp_Conds %>%
  group_by(air_drag,ball,cond_size,id_cond,m,r,rho,cd,TTC,id_TTC,v,G,vy,vx,Xi,Yi,id_exp,label,t_max) %>%
  do(xy_drag_model(vh = .$vx, vv = .$vy,C = .$cd,
                   rho = .$rho,m = .$m,radius = .$r,
                   dt = 0.001,g = .$G,vectors = T)) %>%
  ungroup() 

# =============================================================================
# See experimental conditions with ggplot
# =============================================================================
# READ ME: if you want to see the proper figure download "setup.png" at root folder
# =============================================================================
try(image_setup <-  png::readPNG("Setup.png"))

Temp_cont <- Continuous %>%
  group_by(id_exp) %>%
  mutate(cond_size = factor(cond_size,levels = c("cong","incongr"),labels = c("Congruent","Incongruent")),
         ball = factor(ball,levels = c("tennis","basket"),labels = c("Tennis","Basket")),
         air_drag = factor(air_drag,levels = c(0,1),labels = c("Gravity","Gravity + Air Drag")),
         id_TTC = factor(id_TTC, levels = c("Air_Drag_1","Air_Drag_1.2", "Air_Drag_1.4",
                                            "Gravity_1", "Gravity_1.2","Gravity_1.4"),
                         labels = c("G + AD @ iTTC:1 (s)", "G + AD @ iTTC:1.2 (s)", "G + AD @ iTTC:1.4 (s)",
                                    "G @ iTTC:1 (s)", "G @ iTTC:1.2 (s)", "G @ iTTC:1.4 (s)")))
Temp_Exp_Conds <- Exp_Conds %>%
  group_by(id_exp) %>%
  mutate(cond_size = factor(cond_size,levels = c("cong","incongr"),labels = c("Congruent","Incongruent")),
         ball = factor(ball,levels = c("tennis","basket"),labels = c("Tennis","Basket")),
         air_drag = factor(air_drag,levels = c(0,1),labels = c("Gravity","Gravity + Air Drag")),
         id_TTC = factor(id_TTC, levels = c("Air_Drag_1","Air_Drag_1.2", "Air_Drag_1.4",
                                            "Gravity_1", "Gravity_1.2","Gravity_1.4"),
                         labels = c("G + AD @ iTTC:1 (s)", "G + AD @ iTTC:1.2 (s)", "G + AD @ iTTC:1.4 (s)",
                                    "G @ iTTC:1 (s)", "G @ iTTC:1.2 (s)", "G @ iTTC:1.4 (s)")))



if (exists("image_setup")){
  Setup_Plot <- plot_grid(
    ggplot(Temp_cont %>% filter(ball == "Basket"),aes(x,y+0.7, group = label, color = v)) +
      annotation_custom(rasterGrob(image_setup,
                                   width = unit(1,"npc"),
                                   height = unit(1,"npc")),
                        -Inf, Inf, -Inf, Inf) +
      geom_line() +
      coord_cartesian(ylim=c(0,max(Temp_cont$y)+0.7),xlim=c(-0.25,5.5)) +
      geom_line(data = Temp_cont %>%
                  filter(round(t,3) > round(t_max*0.3,3), round(t,3) < round(t_max*0.6,3),
                         ball == "Basket"), aes(x,y+0.7), color = "red") + 
      labs(x = "x (m)",
           y = "y (m)",
           color = "Condition") + 
      ggtitle(label =  "Experimental conditions",
              subtitle = "Red section indicates random oclusion range") +
      guides(color=FALSE)+
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank()),
    plot_shared_legend(
      ggplot(Temp_Exp_Conds,aes(TTC,t_max,color=factor(air_drag),shape=factor(cond_size))) +
        geom_point() +
        facet_wrap(~ball)+
        labs(x = "TTC under no Air Drag",
             y = "Real TTC",
             color = "Acceleration Condition",
             shape = "Ball size") + 
        scale_color_discrete(), 
      
      ggplot(Temp_Exp_Conds,aes(TTC,x_max,color=factor(air_drag),shape=factor(cond_size))) +
        geom_point() +
        facet_wrap(~ball) +
        labs(x = "TTC under no Air Drag",
             y = expression(X[End])) + 
        scale_color_discrete()
    ),
    nrow=2,rel_heights = c(0.6,0.4)
  )
} else{
  Setup_Plot <- plot_grid(
    ggplot(Temp_cont %>% filter(ball == "Basket"),aes(x,y+0.7, group = label, color = v)) +
      geom_line() +
      coord_cartesian(ylim=c(0,max(Temp_cont$y)+0.7),xlim=c(-0.25,5.5)) +
      geom_line(data = Temp_cont %>% 
                  filter(round(t,3) > round(t_max*0.55,3), round(t,3) < round(t_max*0.6,3), ball == "Basket"),
                aes(x,y+0.7), color = "red") + 
      labs(x = "x (m)",
           y = "y (m)",
           color = "Condition") + 
      ggtitle(label =  "Experimental conditions",
              subtitle = "Red section indicates random oclusion range") +
      guides(color=FALSE)+
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank()),
    plot_shared_legend(
      ggplot(Temp_Exp_Conds,aes(TTC,t_max,color=factor(air_drag),shape=factor(cond_size))) +
        geom_point() +
        facet_wrap(~ball)+
        labs(x = "TTC under no Air Drag",
             y = "Real TTC",
             color = "Acceleration Condition",
             shape = "Ball size") + 
        scale_color_discrete(), 
      
      ggplot(Temp_Exp_Conds,aes(TTC,x_max,color=factor(air_drag),shape=factor(cond_size))) +
        geom_point() +
        facet_wrap(~ball) +
        labs(x = "TTC under no Air Drag",
             y = expression(X[End])) + 
        scale_color_discrete()
    ),
    nrow=2,rel_heights = c(0.6,0.4)
  )
}



rm(Temp_cont,Temp_Exp_Conds,image_setup)
Setup_Plot

# save_plot(plot = Setup_Plot,
#           base_width = 6, base_height = 7,
#           filename = "./figures/Setup_Plot.png")

# =============================================================================
# Write experimental conditions table
# =============================================================================
# writexl::write_xlsx(Exp_Conds,"./experiment/Air_Drag.xlsx" )
```

<!-- POWER ANALYSIS -->
<!--
```{r POWER_ANALYSIS, echo=FALSE, eval = F}
# 
# # =============================================================================
# # Bjorn's power analysis using:
# # Rouder, J. N., & Haaf, J. M. (2018). 
# # Power, dominance, and constraint: A note on the appeal of different design traditions. 
# # Advances in Methods and Practices in Psychological Science, 1(1), 19-26.
# # =============================================================================
# # =============================================================================
# # POWER ANALYSIS
# # =============================================================================
# # =============================================================================
# # Check sd for timing task to use in the power analysis
# # Only for between subjects variability!!
# # =============================================================================
# # READ ME:
# # IF YOU JUST DOWNLOADED THIS DATA FROM OSF:
# # First unzip data folder
# # =============================================================================
# Response_Bjorn <- bind_rows(
#   lapply(paste0(Where_Am_I(),"/data_Jorges_Moliner_2019/",
#                 subset(list.files(paste0(Where_Am_I(),"/data_Jorges_Moliner_2019")),
#                        str_detect(list.files(paste0(Where_Am_I(),
#                                                     "/data_Jorges_Moliner_2019")),"Response"))),
#          read.table,
#          header=T))
# 
# within_var <- (Response_Bjorn %>%
#                  filter(id != "Marco") %>%
#                  group_by(id) %>%
#                  filter(rTime < 3, g == unique(Response_Bjorn$g)[3]) %>%
#                  filter(trim(rTime, filter=T)) %>%
#                  summarize(var_rTime = sd(rTime)) %>%
#                  ungroup() %>%
#                  summarize(var = mean(var_rTime)))$var
# 
# between_var <- (Response_Bjorn %>%
#                   filter(id != "Marco") %>%
#                   group_by(id) %>%
#                   filter(rTime < 3, g == unique(Response_Bjorn$g)[3]) %>%
#                   filter(trim(rTime, filter=T)) %>%
#                   summarize(mean = mean(rTime)) %>%
#                   ungroup() %>%
#                   summarise(var = sd(mean)))$var
# 
# var_rtime <- print(paste0("Between var: ",round(between_var,4), "; Within var: ", round(within_var,4)))
# ratio_var_rtime <- print(paste0("Ratio var: ",round(round(within_var,4)/round(between_var,4),2)))
# 
# # =============================================================================
# # Check differnces between gravity and air drag condition
# # =============================================================================
# Diff_Gravity_Air_drag_t <- Exp_Conds$t_max[1:24]-Exp_Conds$t_max[25:48]
# Diff_Gravity_Air_drag_x <- Exp_Conds$x_max[1:24]-Exp_Conds$x_max[25:48]
# 
# min_diff_Gravity_Air_drag_t <- print(paste0("Minimal diff G-Air drag (s): ",round(min(Diff_Gravity_Air_drag_t),4)))
# mean_diff_Gravity_Air_drag_t <- print(paste0("Mean diff G-Air drag (s): ",round(mean(Diff_Gravity_Air_drag_t),4)))
# max_diff_Gravity_Air_drag_t <- print(paste0("Maximal diff G-Air drag (s): ",round(max(Diff_Gravity_Air_drag_t),4)))
# 
# min_diff_Gravity_Air_drag_x <- print(paste0("Minimal diff G-Air drag (m): ",round(min(Diff_Gravity_Air_drag_x),4)))
# mean_diff_Gravity_Air_drag_x <- print(paste0("Mean diff G-Air drag (m): ",round(mean(Diff_Gravity_Air_drag_x),4)))
# max_diff_Gravity_Air_drag_x <- print(paste0("Maximal diff G-Air drag (m): ",round(max(Diff_Gravity_Air_drag_x),4)))
# 
# 
# 
# ### PILOT DATA OF OUR EXPERIMENT
# a <- read.table(header=T,file = "Pilot.txt")
# 
# d <- a %>%
#   mutate(t_error = rtime_timing - t_max,
#          x_error = ball_x_spatial - x_max) %>%
#   filter(abs(t_error) < 1,
#          abs(x_error) < 2)
# 
# # Jaume 36 + 456
# # =============================================================================
# # Get SDs for Power analysis
# # =============================================================================
# mcol=c('black','blue','purple','red','orange')
# mlty=5:1
# ncp=seq(0,4,.01)
# cut=qt(.975,I-1)
# 
# pow=function(I,ncp) {
#   cut=qt(.975,I-1)
#   pt(lower.tail=F,cut,I-1,ncp)+pt(-cut,I-1,ncp)
# }
# 
# b=outer(I,ncp,pow)
# 
# myncp=function(I,K,s2,nu,delta) {
#   a=nu^2*I*K/(K*delta+2*s2)
#   sqrt(a)
# }
# 
# I=c(5,10,15,20,50) #participants
# K=5:250 #observations per participant
# #s2 is intra-subject variability
# #delta is inter-subject variability
# #nu is effect size
# 
# myPower=function(I,K,s2,nu,delta)
# {
#   ncp=sqrt(nu^2*I*K/(K*delta+2*s2))
#   cut=qt(.975,I-1)
#   return(pt(lower.tail=F,cut,I-1,ncp)+pt(-cut,I-1,ncp))	
# }
# 
# myPanel=function(s2,nu,delta)
# {
#   b=outer(I,K,myPower,s2=s2,nu=nu,delta=delta)
#   matplot(K,t(b),typ='l',lty=mlty,lwd=2,col=mcol,ylim=c(0,1),ylab="Power",xlab="Trials Per Condition")
#   K0=1000/I
#   pow0=myPower(I,K0,s2,nu,delta)
#   points(K0,pow0,col=mcol,pch=19,cex=1.3)
#   return(pow0)
# }
# 
# 
# # =============================================================================
# # POWER ANALYSIS HIPOTHESES:
# # 1a) and 1b)
# # We use:
# #    the pooled SD from pilot subject as intra-subject variability (s2)
# #    the variability from the timing data collected in Jörges & López-Moliner (2009) 
# #        as an estimate of the inter-subject variability (delta) in the timing task;
# #        we assume that the ratio between intra- and inter-subject variability will be
# #        the same for the spatial task (about one third)
# #    the differences between the expected error for the air drag condition and the 
# #        expected error for the no air drag condition as mean (nu) 
# # =============================================================================
# 
# # =============================================================================
# # Temporal task 
# # =============================================================================
# png('./PowerAnalysis/PowerAnalysis_Hypotheses1.png',width=6,height=6,units = "in",res = 300)
# #pdf('PowerAnalysis/PowerAnalysis_Hypotheses1.pdf',width=6,height=6)
# #tiff('PowerAnalysis/PowerAnalysis_Hypotheses1.tiff',width=6,height=6)
# par(mfrow=c(2,3))
# 
# myPanel(s2=sd(d$t_error[d$TTC == 1.0])^2,
#         nu=round(min(Diff_Gravity_Air_drag_t),4),
#         delta=between_var^2) 
# mtext(side=3,adj=0,cex=1,"A: Time (smallest diff.)")
# 
# myPanel(s2=sd(d$t_error[d$TTC == 1.2])^2,
#         nu=round(mean(Diff_Gravity_Air_drag_t),4),
#         delta=between_var^2) 
# mtext(side=3,adj=0,cex=1,"A: Time (mean diff.)")
# 
# myPanel(s2=sd(d$t_error[d$TTC == 1.4])^2,
#         nu=round(max(Diff_Gravity_Air_drag_t),4),
#         delta=between_var^2)
# mtext(side=3,adj=0,cex=1,"A: Time (biggest diff.)")
# 
# par(xpd=T)
# legend(75,0.55,title="# of People",legend=I,lwd=2,col=mcol,lty=mlty,bg="white")
# 
# # =============================================================================
# # Spatial task
# # =============================================================================
# 
# myPanel(s2=sd(d$x_error[d$TTC == 1.0])^2,
#         nu=round(min(Diff_Gravity_Air_drag_x),4),
#         delta=(sd(d$x_error[d$TTC == 1.0])/3.25)^2) 
# mtext(side=3,adj=0,cex=1,"B: Space (smallest diff.)")
# 
# myPanel(s2=sd(d$x_error[d$TTC == 1.2])^2,
#         nu=round(mean(Diff_Gravity_Air_drag_x),4),
#         delta=(sd(d$x_error[d$TTC == 1.2])/3.25)^2) 
# mtext(side=3,adj=0,cex=1,"B: Space (mean diff.)")
# 
# myPanel(s2=sd(d$x_error[d$TTC == 1.4])^2,
#         nu=0.091,
#         delta=(sd(d$x_error[d$TTC == 1.4])/3.25)^2) #case two
# mtext(side=3,adj=0,cex=1,"B: Space (biggest diff.)")
# 
# par(xpd=T)
# legend(75,0.55,title="# of People",legend=I,lwd=2,col=mcol,lty=mlty,bg="white")
# dev.off()
# 
# # =============================================================================
# # POWER ANALYSIS HIPOTHESES:
# # 2a) and 2b)
# # We use: 
# #    the pooled SD from both pilot subjects as intra-subject variability (s2)
# #    the variability from the timing data collected in Jörges & López-Moliner (2009) 
# #        as an estimate of the inter-subject variability (delta) in the timing task;
# #        we assume that the ratio between intra- and inter-subject variability will be
# #        the same for the spatial task (about one third)
# #    the physical differences between congruent and incongruent trials as mean (nu). 
# # =============================================================================
# 
# H2 = Exp_Conds %>%
#   filter(air_drag == 1, ball == "tennis")
# 
# H2_t_1.4 <- abs(mean(H2$t_max[H2$cond_size == "cong" & H2$TTC == 1.4]) - 
#                   mean(H2$t_max[H2$cond_size == "incongr" & H2$TTC == 1.4]))
# H2_t_1.2 <- abs(mean(H2$t_max[H2$cond_size == "cong" & H2$TTC == 1.2]) - 
#                   mean(H2$t_max[H2$cond_size == "incongr" & H2$TTC == 1.2]))
# H2_t_1.0 <- abs(mean(H2$t_max[H2$cond_size == "cong" & H2$TTC == 1.0]) - 
#                   mean(H2$t_max[H2$cond_size == "incongr" & H2$TTC == 1.0]))
# 
# H2_x_1.4 <- abs(mean(H2$x_max[H2$cond_size == "cong" & H2$TTC == 1.4]) - 
#                   mean(H2$x_max[H2$cond_size == "incongr" & H2$TTC == 1.4]))
# H2_x_1.2 <- abs(mean(H2$x_max[H2$cond_size == "cong" & H2$TTC == 1.2]) - 
#                   mean(H2$x_max[H2$cond_size == "incongr" & H2$TTC == 1.2]))
# H2_x_1.0 <- abs(mean(H2$x_max[H2$cond_size == "cong" & H2$TTC == 1.0]) - 
#                   mean(H2$x_max[H2$cond_size == "incongr" & H2$TTC == 1.0]))
# 
# # =============================================================================
# # Temporal task 
# # =============================================================================
# png('./PowerAnalysis/PowerAnalysis_Hypotheses2.png',width=6,height=6,units = "in",res = 300)
# #pdf('PowerAnalysis/PowerAnalysis_Hypotheses2.pdf',width=6,height=6)
# #tiff('PowerAnalysis/PowerAnalysis_Hypotheses2.tiff',width=6,height=6)
# par(mfrow=c(2,3))
# 
# 
# myPanel(s2=sd(d$t_error[d$TTC == 1.0])^2,
#         nu=H2_t_1.0,
#         delta=between_var^2) 
# mtext(side=3,adj=0,cex=1,"Time (TTC=1.0s)")
# 
# myPanel(s2=sd(d$t_error[d$TTC == 1.2])^2,
#         nu=H2_t_1.2,
#         delta=between_var^2) 
# mtext(side=3,adj=0,cex=1,"Time (TTC=1.2s)")
# 
# myPanel(s2=sd(d$t_error[d$TTC == 1.4])^2,
#         nu=H2_t_1.4,
#         delta=between_var^2)
# mtext(side=3,adj=0,cex=1,"Time (TTC=1.4s)")
# 
# par(xpd=T)
# legend(75,0.55,title="# of People",legend=I,lwd=2,col=mcol,lty=mlty,bg="white")
# 
# 
# # =============================================================================
# # Spatial task
# # =============================================================================
# 
# myPanel(s2=sd(d$x_error[d$TTC == 1.0])^2,
#         nu=H2_x_1.0,
#         delta=(sd(d$x_error[d$TTC == 1.0])/3.25)^2) 
# mtext(side=3,adj=0,cex=1,"Space (TTC=1.0s)")
# 
# myPanel(s2=sd(d$x_error[d$TTC == 1.2])^2,
#         nu=H2_x_1.2,
#         delta=(sd(d$x_error[d$TTC == 1.2])/3.25)^2) 
# mtext(side=3,adj=0,cex=1,"Space (TTC=1.2s)")
# 
# myPanel(s2=sd(d$x_error[d$TTC == 1.4])^2,
#         nu=H2_x_1.4,
#         delta=(sd(d$x_error[d$TTC == 1.4])/3.25)^2) #case two
# mtext(side=3,adj=0,cex=1,"Space (TTC=1.4s)")
# 
# par(xpd=T)
# legend(75,0.55,title="# of People",legend=I,lwd=2,col=mcol,lty=mlty,bg="white")
# dev.off()
```
-->
<!-- READ AND PREPARE DATA -->

```{r, READ_AND_PREPARE}
set.seed(80085)
# # =============================================================================
# # Analysis Experiment
# # =============================================================================
# # Function to read datasets
# # =============================================================================
# read_datasets <- function(identifier){
#   id <- list.dirs(Where_Am_I(),recursive = T)
#   trial_datasets <- list(NULL)
#   it <- 1
#   for (i in identifier){
#     df <- file.info(list.files(paste0(Where_Am_I(),"./data/"), full.names = T,recursive = T))
#     df <- df[stringr::str_detect(rownames(df),paste0("./data//",i,"/",paste0(i,"_trial_"))),]
#     df <- rownames(df[which.max(df$ctime),])
#     if (!is.na(df[1])){
#       trial_datasets[[it]] <- read.table(df,header=T)
#     }
#     it = it +1
#   }
#   return(bind_rows(trial_datasets))
# }
# 
# # =============================================================================
# # Function to read continuous datasets
# # =============================================================================
# read_datasets_cont <- function(identifier){
#   id <- list.dirs(Where_Am_I(),recursive = T)
#   trial_datasets <- list(NULL)
#   it <- 1
#   for (i in identifier){
#     df <- file.info(list.files(paste0(Where_Am_I(),"./data/"), full.names = T,recursive = T))
#     df <- df[stringr::str_detect(rownames(df),paste0("./data//",i,"/",paste0(i,"_cont_"))),]
#     df <- rownames(df[which.max(df$ctime),])
#     if (!is.na(df[1])){
#       trial_datasets[[it]] <- read.table(df,header=T)
#     }
#     it = it +1
#   }
#   return(bind_rows(trial_datasets))
# }
# # =============================================================================
# # Read dataset
# # =============================================================================
# # Subjects identifiers
# # =============================================================================
# id <- c("AAM","ADP","AGB","AMM","AMV",
#         "BPB","CCG","CDM","EMM","JBG",
#         "LRC","LRG","MLM","MOG","MVA",
#         "NPT","RMV","SFA","SRT","TMM") #participants ids as string
# 
# AD <- read_datasets(paste0(id)) %>%
#   mutate(block = ifelse(trial < max(trial)/3, 1,
#                         ifelse(trial < max(trial)*2/3, 2 , 3))) %>%
#   select(-visible)
# # =============================================================================
# # Read continuous dataset for temporal visibility variable
# # =============================================================================
# AD <- right_join(AD,read_datasets_cont(id) %>%
#                    group_by(id,trial) %>%
#                    summarize(visible = first(visible)),by=c("id","trial"))%>%
#   select(-vx)
# # =============================================================================
# # This should be runned once, then read: "All_Data_Air_Drag.txt"
# # =============================================================================
# AD_modeled <- right_join(AD ,
#                          data.frame(label = 1:48,
#                                     vx = rep(c(3,3.5),24)),
#                          by = "label") %>%
#   group_by(air_drag,ball,cond_size,id_cond,m,r,rho,cd,TTC,id_TTC,v,G,vy,vx,Xi,Yi,label,visible,trial,id, air_drag) %>%
#   do(xy_drag_model(vh = .$vx, vv = .$TTC*.$G/2,C = .$cd,
#                    rho = .$rho,m = .$m,radius = .$r,
#                    dt = 0.001,g = .$G,
#                    vectors = F, visible = .$visible)) %>%
#   summarize(x_max_model = max(x),
#             y_max_model = max(y),
#             t_max_model = max(t))  %>%
#   ungroup() 
# 
# collapsed <- right_join(bind_rows(AD) ,AD_modeled %>%
#                          select(x_max_model,y_max_model,t_max_model,vx,id,trial),
#                        by = c("trial","id"))


# =============================================================================
# Round before saving "All_Data_Air_Drag.txt"
# =============================================================================
# library(dplyr)
# write.table(x = collapsed,file = "All_Data_Air_Drag.txt")
# write.table(x = collapsed %>% mutate_if(is.numeric, round, digits=4), file =  "All_Data_Air_Drag.txt")
collapsed <- read.table(file = "Data/All_Data_Air_Drag.txt", header = T)

# =============================================================================
# Obtain VD's such as errors and ratios
# =============================================================================
air_drag <-  collapsed %>%
  select(trial,x_max,y_max,t_max,vx,
         x_max_model,t_max_model,y_max_model,
         G,ball,cond_size,r,air_drag,label,
         random_x,rtime_timing,rtime_spatial,ball_x_spatial,ball_x_timing,
         id,TTC,cond_size,visible) %>%
  # Raw differneces
  mutate(terror = rtime_timing-t_max-0.049,
         xerror = ball_x_spatial - x_max,
  # Differences with model modelling AD at oclusion
         xerror_model = ball_x_spatial - x_max_model,
         terror_model = rtime_timing-t_max_model-0.049,
  # Ratio Raw
         xerror_ratio = xerror / x_max,
         terror_ratio = terror / t_max,
  # Ratio Model
         xerror_ratio_model = xerror_model / x_max_model,
         terror_ratio_model = terror_model / t_max_model,
         cond_size = factor(cond_size,levels = c("cong","incongr"),
                            labels = c("Congruent","Incongruent")),
         ball = factor(ball,levels = c("tennis","basket"),
                       labels = c("Tennis","Basket")),
         air_drag = ordered(factor(air_drag),levels = c(0,1),
                            labels = c("Gravity","Gravity + Air_Drag"))
  ) %>%
  group_by(id,label) %>%
  filter(abs(terror) < 1,
         abs(xerror) < 2) %>%
  filter(trim(terror, filter = T)) %>%
  filter(trim(xerror, filter = T))

```


<!-- RESULTS -->

```{r}
# =============================================================================
# PREVIOUS CHECKS!
# =============================================================================
# Is timing task biased by visibility?
# =============================================================================
ggplot(air_drag,aes(visible,rtime_timing, group = factor(TTC))) +
  facet_wrap(vx~TTC, scale="free_x") +
  geom_hline(yintercept = c(1,1.2,1.4), linetype = 2) +
  stat_density2d(aes(alpha=..level.., fill=..level..), size=2, 
                 bins=50, geom="polygon") + 
  geom_smooth(method = "lm")  + 
  scale_fill_gradient(low = "yellow", high = "red") +
  scale_alpha(range = c(0.00, 0.5), guide = FALSE) +
  #geom_density2d(colour="black", bins=10) +
  guides(alpha=FALSE) 

# =============================================================================
# Answer: NO
# =============================================================================


# =============================================================================
# Is spatial task biased by appearence?
# =============================================================================
ggplot(air_drag, aes(ball_x_spatial,random_x, group = air_drag)) + 
  facet_wrap(vx~TTC, scale="free_x") +
  stat_density2d(aes(alpha=..level.., fill=..level..), size=2, 
                 bins=50, geom="polygon") + 
  geom_smooth(method = "lm")  + 
  scale_fill_gradient(low = "yellow", high = "red") +
  scale_alpha(range = c(0.00, 0.5), guide = FALSE) +
  # geom_density2d(colour="black", bins=10) +
  guides(alpha=FALSE) 

# =============================================================================
# Answer: NOT REALLY
# =============================================================================
```

```{r}
fixp <- function(x, dig=3){
  x <- as.data.frame(x)
  
  if(substr(names(x)[ncol(x)],1,2) != "Pr")
    warning("The name of the last column didn't start with Pr. This may indicate that p-values weren't in the last row, and thus, that this function is inappropriate.")
  x[,ncol(x)] <- round(x[,ncol(x)], dig)
  for(i in 1:nrow(x)){
    if(x[i,ncol(x)] == 0)
      x[i,ncol(x)] <- paste0("< .", paste0(rep(0,dig-1), collapse=""), "1")
  }
  return(x)
}
# =============================================================================
# H1: Is Air_Drag taken into account? 
# =============================================================================
# Expected effect: Reduced error for Gravity+Air_Drag condition
# =============================================================================
# Statistics: lmer Reduced error for Gravity+Air_Drag
# Fixed effects: air_drag 
# Random effects: (1|id)
# =============================================================================
# If test model is significantly better than null model, then 
# humans use an internal model of either only gravity, or of gravity AND air drag.
# Otherwise, people switch between both models.
# Furthermore, the intercept of the test model should be zero, and
# the slope should be positive for the timing task,
# and negative for the spatial task
# =============================================================================
# a) Temporal
# =============================================================================
H1_Temporal_lmer <- lmer(terror_ratio ~ air_drag + (1|id), 
                         data = air_drag)
H1_Temporal_lmer_coef <- summary(H1_Temporal_lmer)$coefficients
H1_Temporal_lmer_coef <- fixp(H1_Temporal_lmer_coef)
as.tibble(H1_Temporal_lmer_coef) %>%
  #mutate_if(is.numeric, format, digits=4) %>%
  knitr::kable(digits = 3)

apastats::describe.glm(H1_Temporal_lmer, b.digits = 3)

# =============================================================================
# a) Temporal worst case: Comparing only conditions of TTC = 1.4
# =============================================================================
H1b_Temporal_lmer <- lmer(terror_ratio ~ air_drag + (1|id), 
                         data = air_drag %>% filter(TTC == 1.4))
H1b_Temporal_lmer_coef <- summary(H1b_Temporal_lmer)$coefficients
H1b_Temporal_lmer_coef <- fixp(H1b_Temporal_lmer_coef)
as.tibble(H1b_Temporal_lmer_coef) %>%
  #mutate_if(is.numeric, format, digits=4) %>%
  knitr::kable(digits = 3)
apastats::describe.glm(H1b_Temporal_lmer, b.digits = 3)


# =============================================================================
# b) Spatial
# =============================================================================
H1_Spatial_lmer <- lmer(xerror_ratio ~ air_drag + (1|id),
                        data = air_drag)
H1_Spatial_lmer_coef <- summary(H1_Spatial_lmer)$coefficients
H1_Spatial_lmer_coef <- fixp(H1_Spatial_lmer_coef)
as.tibble(H1_Spatial_lmer_coef) %>%
  #mutate_if(is.numeric, format, digits=4) %>%
  knitr::kable(digits = 3)
apastats::describe.glm(H1_Spatial_lmer, b.digits = 3)

# =============================================================================
# b) Temporal worst case: Comparing only conditions of TTC = 1.4
# =============================================================================
H1b_Spatial_lmer <- lmer(xerror ~ air_drag + (1|id),
                         data = air_drag %>%
                           filter(TTC == 1.4))
H1b_Spatial_lmer_coef <- summary(H1b_Spatial_lmer)$coefficients
H1b_Spatial_lmer_coef <- fixp(H1b_Spatial_lmer_coef)
as.tibble(H1b_Spatial_lmer_coef) %>%
  #mutate_if(is.numeric, format, digits=4) %>%
  knitr::kable(digits = 3)
apastats::describe.glm(H1b_Spatial_lmer, b.digits = 3)
```


```{r}
# =============================================================================
# Plotting
# =============================================================================
# In this plots I used Wilcoxon test to compare means (non-parametic) due to 
# non normal distributions. And then I used "adjust_pvalue()" which uses "holm"
# p_value corrections.
# =============================================================================
# a) Temporal by participant
# =============================================================================
stat_test_t <- air_drag %>%
  group_by(id) %>%
  mutate(k = rtime_timing/t_max) %>%
  wilcox_test(k ~ air_drag) %>%
  adjust_pvalue() %>%
  mutate(y.position = 1.8,
         color_p = ifelse(p.adj < 0.05, "red","black"))

ggplot(air_drag %>% mutate(k = rtime_timing/t_max), aes(air_drag,k,color = factor(air_drag))) +
  geom_hline(linetype = 2, yintercept = 1) +
  geom_jitter(alpha = 0.025, width = 0.1) +
  geom_flat_violin(alpha = 0.5)+
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",color = "red") +
  facet_wrap(~id) +
  # coord_cartesian(ylim = c(-1,1)) +
  scale_color_discrete(name = "Condition") +
  theme(legend.position = "bottom") +
  stat_pvalue_manual(stat_test_t, label = "p.adj", color = "color_p") +
  labs(x = NULL,
       y = "Timing Error ratio")

# =============================================================================
# a) Temporal: Only TTC = 1.4
# =============================================================================
stat_test_t_b <- air_drag %>%
  ungroup() %>%
  filter(TTC == 1.4) %>%
  mutate(k = rtime_timing/t_max) %>%
  wilcox_test(k ~ air_drag) %>%
  adjust_pvalue() %>%
  mutate(y.position = 1.8,
         color_p = ifelse(p.adj < 0.05, "red","black"))


ggplot(air_drag %>%
         mutate(k = rtime_timing/t_max) %>%
         filter(TTC == 1.4), aes(air_drag,k,color = factor(air_drag))) +
  geom_hline(linetype = 2, yintercept = 1) + 
  geom_jitter(alpha = 0.025, width = 0.1) +
  geom_flat_violin(alpha = 0.5)+ 
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",color = "red") +  
  scale_color_discrete(name = "Condition") + 
  theme(legend.position = "bottom") + 
  stat_pvalue_manual(stat_test_t_b, label = "p.adj",color = "color_p") +
  labs(x = NULL,
       y = "Timing Error ratio") 


# =============================================================================
# Plotting
# =============================================================================
# =============================================================================
# a) Spatial by participant
# =============================================================================
stat_test_x <- air_drag %>%
  group_by(id) %>%
  mutate(k = ball_x_spatial/x_max) %>%
  wilcox_test(k ~ air_drag) %>%
  adjust_pvalue() %>%
  mutate(y.position = 1.3,
         color_p = ifelse(p.adj < 0.05, "red","black"))

ggplot(air_drag %>%
         mutate(k = ball_x_spatial/x_max) ,
       aes(air_drag,k,color = factor(air_drag))) +
  geom_hline(linetype = 2, yintercept = 1) +
  geom_jitter(alpha = 0.025, width = 0.1) +
  geom_flat_violin(alpha = 0.5)+
  #ggpubr::stat_compare_means(method = "wilcox.test", label.y = 1.4,aes(label=..p.adj..))+
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",color = "red") +
  facet_wrap(~id) +
  # coord_cartesian(ylim = c(-1,1)) +
  scale_color_discrete(name = "Condition") +
  theme(legend.position = "bottom") +
  stat_pvalue_manual(stat_test_x, label = "p.adj", color = "color_p") +
  labs(x = NULL,
       y = "Spatial Error ratio")


# =============================================================================
# a) Spatial: Only TTC = 1.4
# =============================================================================
stat_test_x_b <- air_drag %>%
  ungroup() %>%
  filter(TTC == 1.4) %>%
  mutate(k = ball_x_spatial/x_max) %>%
  t_test(k ~ air_drag) %>%
  adjust_pvalue() %>%
  mutate(y.position = 1.3,
         color_p = ifelse(p.adj < 0.05, "red","black"))

ggplot(air_drag %>%
         mutate(k = ball_x_spatial/x_max) %>% 
         filter(TTC == 1.4), aes(air_drag,k,color = factor(air_drag))) +
  geom_hline(linetype = 2, yintercept = 1) + 
  geom_jitter(alpha = 0.025, width = 0.1) +
  geom_flat_violin(alpha = 0.5)+ 
  #ggpubr::stat_compare_means(method = "wilcox.test", label.y = 1.4)+
  stat_summary(fun.data = "mean_cl_normal", geom = "pointrange",color = "red") +  
  # coord_cartesian(ylim = c(-1,1)) + 
  scale_color_discrete(name = "Condition") + 
  theme(legend.position = "bottom")  + 
  stat_pvalue_manual(stat_test_x_b, label = "p.adj", color = "color_p") +
  labs(x = NULL,
       y = "Spatial Error ratio")

```


```{r}
# =============================================================================
# Response variability, errors and conditions
# =============================================================================
air_drag_sum <- air_drag %>%
  group_by(TTC,vx,id,air_drag,ball,cond_size) %>%
  mutate(sd_timing = sd(rtime_timing),
            sd_spatial = sd(ball_x_spatial),
            visible = mean(visible),
            terror_ratio = mean(rtime_timing)/mean(t_max),
            xerror_ratio = mean(ball_x_spatial)/mean(x_max),
            ratio_t = sd_timing/mean(t_max),
            ratio_x = sd_spatial/mean(x_max),
            #xerror_t_ratio = mean(ball_x_spatial)/mean(x_max),
            t_max = mean(t_max),
            x_max = mean(x_max),
            terror = mean(terror),
            xerror= mean(xerror),
            visible = mean(visible))
            
air_drag_participant <- air_drag_sum %>%
  group_by(id) %>%
  summarize_all(.funs = "mean")
    
        
air_drag_ratios <- air_drag_sum %>%
  ungroup() %>%
  select(-id,-cond_size,-ball) %>%
  summarize_all(.funs = "mean")


mean_ratio_sd_air_Drag <- air_drag_sum %>%
  group_by(id) %>%
  mutate(max_xerror = mean_cl_normal(ratio_x)$ymax,
            min_xerror = mean_cl_normal(ratio_x)$ymin,
            ratio_x = mean_cl_normal(ratio_x)$y,
            max_terror = mean_cl_normal(ratio_t)$ymax,
            min_terror = mean_cl_normal(ratio_t)$ymin,
            ratio_t = mean_cl_normal(ratio_t)$y)



# =============================================================================
# a) Timing: Variability ratio vs. error ratio 
# =============================================================================
ggplot(air_drag_sum,aes(terror_ratio,ratio_t,fill = id)) + 
  geom_abline(linetype = 2) +
  geom_point(alpha = 0.25, shape = 21) + 
  geom_point(data= air_drag_participant, size = 3, shape = 21) +
  stat_cor(data = air_drag_participant, aes(group = 0)) + 
  labs(x = expression(rt/t[max]),
       y = expression(sigma[t]/t[max]),
       color = NULL) + 
  guides(fill = F) +
  scale_fill_viridis_d()

# =============================================================================
# b) Spatial: Variability ratio vs. error ratio 
# =============================================================================

ggplot(air_drag_sum,aes(xerror_ratio,ratio_x,fill = id)) + 
  geom_abline(linetype = 2) +
  geom_point(alpha = 0.25, shape = 21) + 
  geom_point(data= air_drag_participant, size = 3, shape = 21) +
  stat_cor(data = air_drag_participant, aes(group = 0)) + 
  labs(x = expression(rx/x[max]),
       y = expression(sigma[x]/x[max]),
       color = NULL) + 
  guides(fill = F) +
  scale_fill_viridis_d() 

# =============================================================================
# c) Timing variability ratio vs. Spatial variability ratio
# =============================================================================

ggplot(air_drag_sum,aes(ratio_x,ratio_t,fill = id)) + 
  geom_abline(linetype = 2) + 
  geom_point(alpha = 0.25, shape = 21) + 
  geom_point(data= air_drag_participant, size = 3, shape = 21) +
  ggpubr::stat_cor(aes(group = 0))+ 
  labs(title = paste0("Spatial ratio: ", round( air_drag_ratios$ratio_x[1],3),
                      "\nTemporal ratio: ", round( air_drag_ratios$ratio_t[1],3)),
       x = expression(sigma[x]/x[max]),
       y = expression(sigma[t]/t[max]),
       color = NULL) + 
  scale_fill_viridis_d() +
  guides(fill = FALSE) +
  # geom_errorbarh(data = mean_ratio_sd_air_Drag, 
  #                aes(x = ratio_x,
  #                    xmax = max_xerror,   
  #                    xmin = min_xerror)) +   
  # geom_errorbar(data = mean_ratio_sd_air_Drag,aes(y = ratio_t,
  #                    ymax = max_terror,
  #                    ymin = min_terror)) +
  theme_minimal(12)


# =============================================================================
# c) Terror ratio vs. Xerror ratio
# =============================================================================
ggplot(air_drag_sum  ,aes(xerror_ratio,terror_ratio,fill = id)) + 
  geom_abline(linetype = 2) + 
  geom_point(alpha = 0.25, shape = 21) + 
  geom_point(data= air_drag_participant, size = 3, shape = 21) +
  ggpubr::stat_cor(aes(group = 0))+ 
  labs(x = expression(r[x]/x[max]),
       y = expression(r[t]/t[max]),
       color = NULL) + 
  scale_fill_viridis_d() +
  #guides(fill = FALSE) +
  #facet_wrap(~id) +
  theme_minimal(12)

```



